In [93]:
import pandas as pd

In [94]:
# 데이터 불러오기
df = pd.read_csv('data/측정좌표_ID.csv')
df.head()

,Unnamed: 0,지역명,측정소명,주소,운영기관,설치년도,위도,경도,광역시도,시군구,구읍,중복확인
0,0,서울,강남구,서울 강남구 학동로 426 강남구청 별관 1동,서울특별시보건환경연구원,1978.0,37.517968,127.047060,서울특별시,강남구,학동로,서울 강남
1,1,서울,강동구,서울 강동구 구천면로 42길 59 천호1동 주민센터,서울특별시보건환경연구원,1997.0,37.545021,127.136799,서울특별시,강동구,구천면로,서울 강동
2,2,서울,강북구,서울 강북구 삼양로 139길 49 우이동 주민센터,서울특별시보건환경연구원,1997.0,37.647934,127.011870,서울특별시,강북구,삼양로,서울 강북
3,3,서울,강서구,서울 강서구 강서로 45 다길 71 화곡3동 푸른들청소년도서관,서울특별시보건환경연구원,1992.0,37.544670,126.835179,서울특별시,강서구,강서로,서울 강서
4,4,서울,관악구,서울 관악구 신림동길 14 신림동 주민센터,서울특별시보건환경연구원,1979.0,37.487396,126.927114,서울특별시,관악구,신림동길,서울 관악

In [95]:
df = df.drop_duplicates(subset="중복확인")
df

,Unnamed: 0,지역명,측정소명,주소,운영기관,설치년도,위도,경도,광역시도,시군구,구읍,중복확인
0,0,서울,강남구,서울 강남구 학동로 426 강남구청 별관 1동,서울특별시보건환경연구원,1978.0,37.517968,127.047060,서울특별시,강남구,학동로,서울 강남
1,1,서울,강동구,서울 강동구 구천면로 42길 59 천호1동 주민센터,서울특별시보건환경연구원,1997.0,37.545021,127.136799,서울특별시,강동구,구천면로,서울 강동
2,2,서울,강북구,서울 강북구 삼양로 139길 49 우이동 주민센터,서울특별시보건환경연구원,1997.0,37.647934,127.011870,서울특별시,강북구,삼양로,서울 강북
3,3,서울,강서구,서울 강서구 강서로 45 다길 71 화곡3동 푸른들청소년도서관,서울특별시보건환경연구원,1992.0,37.544670,126.835179,서울특별시,강서구,강서로,서울 강서
4,4,서울,관악구,서울 관악구 신림동길 14 신림동 주민센터,서울특별시보건환경연구원,1979.0,37.487396,126.927114,서울특별시,관악구,신림동길,서울 관악
...,...,...,...,...,...,...,...,...,...,...,...,...
503,503,전북,운봉읍,전라북도 남원시 운봉읍 황산로 1083 운봉읍 행정복지센터 옥상,전라북도보건환경연구원,2021.0,35.439304,127.529236,전라북도,남원시,운봉읍,남원
505,505,전북,장수읍,전라북도 장수군 장수읍 호비로 10 장수군청 옥상,전라북도보건환경연구원,2018.0,35.646981,127.521582,전라북도,장수군,장수읍,장수
507,507,전북,진안읍,전북 진안군 진안읍 진무로 1189 진안군 보건소 옥상,전라북도보건환경연구원,2017.0,35.797309,127.434775,전라북도,진안군,진안읍,진안
514,514,제주,강정동,제주특별자치도 서귀포시 일주서로 166 제주 유나이티드 연습구장 옆(지상) (강정동),제주특별자치도보건환경연구원,NaN,33.253333,126.490949,제주특별자치도,서귀포시,일주서로,서귀포
519,519,제주,애월읍,제주특별자치도 제주시 애월읍 고내리 1319 애월근린공원 옆,제주특별자치도보건환경연구원,NaN,33.464689,126.331494,제주특별자치도,제주시,애월읍,제주

In [96]:
# csv파일로 저장
df.to_csv('data/측정좌표_중복.csv', encoding='utf-8', index=False)

In [97]:
# 데이터 불러오기
pop = pd.read_csv('data/카토그램.csv')
pop.head()

   Unnamed: 0     ID   광역시도  시군구  격자 X  격자 Y  y  x
0           0  서울 종로  서울특별시  종로구    60   127  4  6
1           1  서울 중구  서울특별시   중구    60   127  5  6
2           2  서울 용산  서울특별시  용산구    60   126  6  6
3           3  서울 성동  서울특별시  성동구    61   127  5  7
4           4  서울 광진  서울특별시  광진구    62   126  6  7

In [98]:
# 측정소에만 있는 데이터
df_only = df[~df['중복확인'].isin(pop['ID'])]
df_only.head(5)

Empty DataFrame
Columns: [Unnamed: 0, 지역명, 측정소명, 주소, 운영기관, 설치년도, 위도, 경도, 광역시도, 시군구, 구읍, 중복확인]
Index: []

In [99]:
# 카토그램에만 있는 데이터
only = pop[~pop['ID'].isin(df['중복확인'])]
only

Empty DataFrame
Columns: [Unnamed: 0, ID, 광역시도, 시군구, 격자 X, 격자 Y, y, x]
Index: []

In [102]:
df.head(3)

,Unnamed: 0,지역명,측정소명,주소,운영기관,설치년도,위도,경도,광역시도,시군구,구읍,중복확인
0,0,서울,강남구,서울 강남구 학동로 426 강남구청 별관 1동,서울특별시보건환경연구원,1978.0,37.517968,127.047060,서울특별시,강남구,학동로,서울 강남
1,1,서울,강동구,서울 강동구 구천면로 42길 59 천호1동 주민센터,서울특별시보건환경연구원,1997.0,37.545021,127.136799,서울특별시,강동구,구천면로,서울 강동
2,2,서울,강북구,서울 강북구 삼양로 139길 49 우이동 주민센터,서울특별시보건환경연구원,1997.0,37.647934,127.011870,서울특별시,강북구,삼양로,서울 강북

In [103]:
# 필요없는 컬럼 삭제
df.drop(columns=['운영기관', '설치년도'], inplace=True)
df

,Unnamed: 0,지역명,측정소명,주소,위도,경도,광역시도,시군구,구읍,중복확인
0,0,서울,강남구,서울 강남구 학동로 426 강남구청 별관 1동,37.517968,127.047060,서울특별시,강남구,학동로,서울 강남
1,1,서울,강동구,서울 강동구 구천면로 42길 59 천호1동 주민센터,37.545021,127.136799,서울특별시,강동구,구천면로,서울 강동
2,2,서울,강북구,서울 강북구 삼양로 139길 49 우이동 주민센터,37.647934,127.011870,서울특별시,강북구,삼양로,서울 강북
3,3,서울,강서구,서울 강서구 강서로 45 다길 71 화곡3동 푸른들청소년도서관,37.544670,126.835179,서울특별시,강서구,강서로,서울 강서
4,4,서울,관악구,서울 관악구 신림동길 14 신림동 주민센터,37.487396,126.927114,서울특별시,관악구,신림동길,서울 관악
...,...,...,...,...,...,...,...,...,...,...
503,503,전북,운봉읍,전라북도 남원시 운봉읍 황산로 1083 운봉읍 행정복지센터 옥상,35.439304,127.529236,전라북도,남원시,운봉읍,남원
505,505,전북,장수읍,전라북도 장수군 장수읍 호비로 10 장수군청 옥상,35.646981,127.521582,전라북도,장수군,장수읍,장수
507,507,전북,진안읍,전북 진안군 진안읍 진무로 1189 진안군 보건소 옥상,35.797309,127.434775,전라북도,진안군,진안읍,진안
514,514,제주,강정동,제주특별자치도 서귀포시 일주서로 166 제주 유나이티드 연습구장 옆(지상) (강정동),33.253333,126.490949,제주특별자치도,서귀포시,일주서로,서귀포
519,519,제주,애월읍,제주특별자치도 제주시 애월읍 고내리 1319 애월근린공원 옆,33.464689,126.331494,제주특별자치도,제주시,애월읍,제주

In [104]:
# csv파일로 저장
df.to_csv('data/측정좌표_최종.csv', encoding='utf-8', index=False)