In [2]:
import pandas as pd

In [3]:
pop = pd.read_csv('data/측정좌표_최종.csv', encoding='utf-8')
pop.head()

,Unnamed: 0,지역명,측정소명,주소,위도,경도,광역시도,시군구,구읍,중복확인
0,0,서울,강남구,서울 강남구 학동로 426 강남구청 별관 1동,37.517968,127.047060,서울특별시,강남구,학동로,서울 강남
1,1,서울,강동구,서울 강동구 구천면로 42길 59 천호1동 주민센터,37.545021,127.136799,서울특별시,강동구,구천면로,서울 강동
2,2,서울,강북구,서울 강북구 삼양로 139길 49 우이동 주민센터,37.647934,127.011870,서울특별시,강북구,삼양로,서울 강북
3,3,서울,강서구,서울 강서구 강서로 45 다길 71 화곡3동 푸른들청소년도서관,37.544670,126.835179,서울특별시,강서구,강서로,서울 강서
4,4,서울,관악구,서울 관악구 신림동길 14 신림동 주민센터,37.487396,126.927114,서울특별시,관악구,신림동길,서울 관악

In [4]:
df = pd.read_csv('data/카토그램.csv', encoding='utf-8')
df.head()

   Unnamed: 0     ID   광역시도  시군구  격자 X  격자 Y  y  x
0           0  서울 종로  서울특별시  종로구    60   127  4  6
1           1  서울 중구  서울특별시   중구    60   127  5  6
2           2  서울 용산  서울특별시  용산구    60   126  6  6
3           3  서울 성동  서울특별시  성동구    61   127  5  7
4           4  서울 광진  서울특별시  광진구    62   126  6  7

In [6]:
# '중복확인' 열과 'ID' 열이 일치하는 경우, '측정소명' 열을 일치하는 행에 추가
df['측정소명'] = df['ID'].map(pop.set_index('중복확인')['측정소명'])
df

     Unnamed: 0      ID     광역시도  시군구  격자 X  격자 Y  y   x 측정소명
0             0   서울 종로    서울특별시  종로구    60   127  4   6  종로구
1             1   서울 중구    서울특별시   중구    60   127  5   6   중구
2             2   서울 용산    서울특별시  용산구    60   126  6   6  용산구
3             3   서울 성동    서울특별시  성동구    61   127  5   7  성동구
4             4   서울 광진    서울특별시  광진구    62   126  6   7  광진구
..          ...     ...      ...  ...   ...   ... ..  ..  ...
245         245      화천  강원특별자치도  화천군    72   139  0   8  화천읍
246         246      양구  강원특별자치도  양구군    77   139  0   9  양구읍
247         247      인제  강원특별자치도  인제군    80   138  1   9  인제읍
248         248  고성(강원)  강원특별자치도  고성군    85   145  0  10   상리
249         249      양양  강원특별자치도  양양군    88   138  2  10  양양읍

[250 rows x 9 columns]

In [7]:
# csv파일로 저장
df.to_csv('data/카토그램_최종.csv', encoding='utf-8', index=False)